id: P744AEE44
initial_creation_type: input
source_metadata:
  title: Nyangral Nyima Özer Series
  language: zh
  description: 'Texts composed or revealed by the important tertön Nyangral Nyima
    Özer (nyang ral nyi ma ''od zer, 1124–1192):'
  volume:
    593a2cc5658c45ff8ac536a84284bcf2:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    ae14f9f11c814d48b1848c9b2ee77596:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Prayers to Guru Rinpoche
    bf434849d4414e6c9ecc1cd77c68a473:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Prayers to Guru Rinpoche
created_at: '2022-03-01T01:04:34.419631'
last_modified_at: '2022-03-01T01:04:34.419633'
